### PR TITLE
issue #31676 - scriptapi refinements

### PR DESCRIPTION
**Pull request by gilmoskowitz**
- expanded qeventloop exposure
- updated enums and flags
- changed conditional compilation to better reflect qt versions
- added test harness for scriptapi dir
- added ability to track use of deprecated script api calls
- moved translation initialization so `qsTr()` is available to widget scripts

### CODE REVIEW

**Comment by gilmoskowitz** [comment]
jenkins - retest this please

**Comment by bendiy** [comment]
jenkins - retest this please

**Comment by bendiy** [comment]
jenkins - retest this please

**Comment by davidbeauchamp** [comment]
jenkins - retest this please

**Pull request merged**
