### PR TITLE
[34405] Align version 4.12 with published compatibility matrix

### PR DESCRIPTION
**Pull request by andersdd**

### CODE REVIEW

**Comment by ChristopherCotnoir** [comment]
Includes earliest, excludes latest, so should be 11.0 (or something like that, are we properly handling postgres' switch from MAJ.MIN.PAT to MIN.PAT? Had to make changes to the plv8 script for that).

**Comment by andersdd** [comment]
@ChristopherCotnoir I went with the _published_ compatibility matrix.  Regarding the change to Postgres 10 versioning, I figured this issue related to 4.12, and we can make appropriate changes in the 5.0 series to the upper postgres versioning and versioning scheme.

**Comment by gilmoskowitz** [comment]
Chris is right -- the compatibility matrix says 4.12.0-alpha works with 10.x but this code change excludes all of 10.x.

**Comment by andersdd** [comment]
Amended `latest` version check value

**Pull request merged**
