### PR TITLE
[25096] Have isValid return false for empty XComboBoxes

### PR DESCRIPTION
**Pull request by ChristopherCotnoir**

### CODE REVIEW

**Comment by gilmoskowitz** [comment]
@ChristopherCotnoir could you please open a new PR with these changes made against 4_12_x?

**Comment by gilmoskowitz** [comment]
jenkins - retest this please

**Comment by gilmoskowitz** [comment]
OK to merge when CI passes

**Comment by ChristopherCotnoir** [comment]
jenkins - retest this please

**Pull request merged**
