### PR TITLE
Issue 26849: Extract Item Groups populate query to MetaSQL, provide checkbox to show only top level item groups

### PR DESCRIPTION
**Pull request by davidbeauchamp**

### CODE REVIEW

**Comment by davidbeauchamp** [comment]
Requires https://github.com/xtuple/xtuple/pull/2539

**Comment by andersdd** [comment]
Not 100% sure about the extra sFillList - personally think we should remove the int parameter.    But rest of code looks fine +1 code review

**Comment by davidbeauchamp** [comment]
Removed duplicate sFillList(), implemented getParams(), also wrapped delete group code in a QMessageBox to confirm deletion

**Comment by andersdd** [comment]
+1 code review.   Like this feature - very useful

**Pull request merged**
