### PR TITLE
issue #25222, issue #25345 - fix problems editing and using list-type characteristics

### PR DESCRIPTION
**Pull request by gilmoskowitz**

### CODE REVIEW

**Comment by gilmoskowitz** [comment]
@gpazo & @garyhgohoos -  could you both please review this one? it's different than most of our code.

**Comment by gpazo** [comment]
+1 looks good to me

**Comment by garyhgohoos** [comment]
never have gained a good understanding of model/view.  looks ok

**Comment by gilmoskowitz** [comment]
Thanks

**Pull request merged**
